import logging
import os
import shutil
import subprocess
import sys
import tempfile
import time

from minio import Minio


# --- Config ---
MINIO_EP = os.getenv("MINIO_ENDPOINT", "minio:9000")
ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY", "minioadmin")
SECRET_KEY = os.getenv("MINIO_SECRET_KEY", "minioadmin")
JOB_ID = os.getenv("JOB_ID")
OBJECT_KEY = os.getenv("OBJECT_KEY")
BUCKET = "videos"

# --- Logging ---
logging.basicConfig(
	level=logging.INFO,
	format="%(asctime)s [%(levelname)s] %(message)s",
	stream=sys.stdout,
)


def wait_for_minio(max_retries: int = 30, delay: int = 2) -> Minio:
	"""Wait for MinIO to be available with retries."""
	client = Minio(MINIO_EP, ACCESS_KEY, SECRET_KEY, secure=False)

	for attempt in range(max_retries):
		try:
			client.list_buckets()
			logging.info("MinIO is ready")
			return client
		except Exception as e:
			if attempt < max_retries - 1:
				logging.warning(
					f"Waiting for MinIO at {MINIO_EP} "
					f"(attempt {attempt + 1}/{max_retries})..."
				)
				time.sleep(delay)
			else:
				raise RuntimeError(
					f"MinIO not available after {max_retries} attempts: {e}"
				)


def run_whisper(input_file: str, output_dir: str) -> str:
	"""Run Whisper transcription and return path to generated SRT."""
	cmd = [
		"whisper",
		input_file,
		"--model", "small",
		"--output_format", "srt",
		"--output_dir", output_dir,
	]

	try:
		subprocess.run(cmd, check=True, capture_output=True, text=True)
	except subprocess.CalledProcessError as e:
		logging.error(f"Whisper failed: {e.stderr}")
		raise

	# Whisper usually names output after the input stem
	stem = os.path.splitext(os.path.basename(input_file))[0]
	expected_srt = os.path.join(output_dir, f"{stem}.srt")

	if os.path.exists(expected_srt):
		return expected_srt

	# Fallback: search for any .srt in the output dir
	for file in os.listdir(output_dir):
		if file.endswith(".srt"):
			return os.path.join(output_dir, file)

	raise FileNotFoundError("No SRT file generated by Whisper")


def main():
	if not JOB_ID or not OBJECT_KEY:
		logging.error("Missing JOB_ID or OBJECT_KEY environment variables")
		sys.exit(1)

	logging.info(f"Starting transcription for job {JOB_ID}, object {OBJECT_KEY}")
	minio = wait_for_minio()

	tmp_dir = tempfile.mkdtemp()
	local_in = os.path.join(tmp_dir, os.path.basename(OBJECT_KEY))
	local_srt = os.path.join(tmp_dir, f"{JOB_ID}.srt")

	try:
		# Download input
		logging.info(f"Downloading {OBJECT_KEY} from bucket {BUCKET}...")
		minio.fget_object(BUCKET, OBJECT_KEY, local_in)
		logging.info(f"Downloaded to {local_in}")

		# Run Whisper
		logging.info("Running Whisper transcription...")
		generated_srt = run_whisper(local_in, tmp_dir)

		# Move to JOB_ID-named file
		shutil.move(generated_srt, local_srt)
		logging.info(f"SRT file prepared at {local_srt}")

		# Upload to MinIO
		srt_key = f"subtitles/{JOB_ID}.srt"
		logging.info(f"Uploading result to {BUCKET}/{srt_key}...")
		minio.fput_object(BUCKET, srt_key, local_srt)
		logging.info(f"Transcription completed successfully for job {JOB_ID}")

	except Exception:
		logging.exception(f"Job {JOB_ID} failed")
		raise
	finally:
		if os.path.exists(tmp_dir):
			shutil.rmtree(tmp_dir)
			logging.info("Cleaned up temporary files")


if __name__ == "__main__":
	main()
